CC = gcc
CFLAGS = -Wall -Wextra -fprofile-arcs -ftest-coverage -g

all: main

main: main.o
	$(CC) $(CFLAGS) -o main main.o

main.o: main.c
	$(CC) $(CFLAGS) -c main.c

clean:
	@rm -f main main.o main.gcno main.gcda
